# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
